"""create initial tables

Revision ID: 237430d9ef75
Revises: 
Create Date: 2026-09-18 09:51:34.616994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '237430d9ef75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_films_title'), 'films', ['title'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=True)
    op.create_table('screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screens_name'), 'screens', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('showtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showtimes_film_id'), 'showtimes', ['film_id'], unique=False)
    op.create_index(op.f('ix_showtimes_screen_id'), 'showtimes', ['screen_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_reference'), 'bookings', ['reference'], unique=True)
    op.create_index(op.f('ix_bookings_showtime_id'), 'bookings', ['showtime_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('seat_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('showtime_id', 'seat_number')
    )
    op.create_index(op.f('ix_seat_inventory_seat_number'), 'seat_inventory', ['seat_number'], unique=False)
    op.create_index(op.f('ix_seat_inventory_showtime_id'), 'seat_inventory', ['showtime_id'], unique=False)
    op.create_index(op.f('ix_seat_inventory_status'), 'seat_inventory', ['status'], unique=False)
    op.create_table('booking_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('seat_inventory_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['seat_inventory_id'], ['seat_inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'seat_inventory_id')
    )
    op.create_index(op.f('ix_booking_seats_booking_id'), 'booking_seats', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_seats_seat_inventory_id'), 'booking_seats', ['seat_inventory_id'], unique=False)
    op.create_table('holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seat_inventory_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seat_inventory_id'], ['seat_inventory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holds_seat_inventory_id'), 'holds', ['seat_inventory_id'], unique=False)
    op.create_index(op.f('ix_holds_status'), 'holds', ['status'], unique=False)
    op.create_index(op.f('ix_holds_user_id'), 'holds', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_holds_user_id'), table_name='holds')
    op.drop_index(op.f('ix_holds_status'), table_name='holds')
    op.drop_index(op.f('ix_holds_seat_inventory_id'), table_name='holds')
    op.drop_table('holds')
    op.drop_index(op.f('ix_booking_seats_seat_inventory_id'), table_name='booking_seats')
    op.drop_index(op.f('ix_booking_seats_booking_id'), table_name='booking_seats')
    op.drop_table('booking_seats')
    op.drop_index(op.f('ix_seat_inventory_status'), table_name='seat_inventory')
    op.drop_index(op.f('ix_seat_inventory_showtime_id'), table_name='seat_inventory')
    op.drop_index(op.f('ix_seat_inventory_seat_number'), table_name='seat_inventory')
    op.drop_table('seat_inventory')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_showtime_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_showtimes_screen_id'), table_name='showtimes')
    op.drop_index(op.f('ix_showtimes_film_id'), table_name='showtimes')
    op.drop_table('showtimes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_screens_name'), table_name='screens')
    op.drop_table('screens')
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_films_title'), table_name='films')
    op.drop_table('films')
    # ### end Alembic commands ###
