"""add ticket price to showtimes

Revision ID: d3dde6e37100
Revises: 237430d9ef75
Create Date: 2026-09-21 07:03:25.841475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3dde6e37100'
down_revision: Union[str, Sequence[str], None] = '237430d9ef75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtimes', sa.Column('ticket_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showtimes', 'ticket_price')
    # ### end Alembic commands ###
